import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the application — wraps pages with the HTML skeleton and global fonts.
 *
 * This component renders the top-level HTML structure (html lang="en") and a body that
 * applies the Geist Sans and Geist Mono font CSS variables plus `antialiased`. Place
 * page content inside the `children` prop.
 *
 * @param children - React nodes rendered inside the document body
 * @returns The root HTML structure containing `children`
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
